In [9]:
import pandas as pd

ty = pd.read_excel("trend.xlsx", sheet_name=2)
uro = pd.read_excel("trend.xlsx", sheet_name=0)
sp = pd.read_excel("trend.xlsx", sheet_name=1)

In [10]:
ty

,#ty,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,SynTY,M O V I N G A V E R A G E S,...,THESE ARE FOR BREAKOUT,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,CORRELATIONS,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,#Date,Open,High,Low,Close,NC,PC(%),Roll,100.000000,ma10,...,Hi30,Low30,action,position,BrkRet30,NaN,TenThirty,Thirty 100,Eigthy 160,Brkout30
1,19990308,114.46875,114.6875,114.375,114.4375,0.09375,0.08199,0,100.081990,NaN,...,NaN,NaN,NaN,NaN,NaN,TenThirty,1,NaN,NaN,NaN
2,19990309,114.25,115.125,114.125,115,0.5625,0.491535,0,100.573927,NaN,...,NaN,NaN,NaN,NaN,NaN,Thirty 100,NaN,1,NaN,NaN
3,19990310,115.03125,115.125,114.6875,114.875,-0.125,-0.108696,0,100.464608,NaN,...,NaN,NaN,NaN,NaN,NaN,Eigthy 160,NaN,NaN,1,NaN
4,19990311,114.78125,115.09375,114.625,114.875,0,0,0,100.464608,NaN,...,NaN,NaN,NaN,NaN,NaN,Brkout30,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2979,20101227,119.28125,119.953125,119.21875,119.9375,0.4062,0.3399,0,165.143867,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2980,20101228,120.03125,120.1875,118.953125,119.046875,-0.8906,-0.7426,0,163.917509,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2981,20101229,119.03125,120.265625,118.953125,120.25,1.2031,1.0106,0,165.574059,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2982,20101230,120,120.203125,119.578125,119.984375,-0.2656,-0.2209,0,165.208306,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2983,20101231,120.359375,120.484375,119.9375,120.34375,0.3594,0.2995,0,165.703105,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
ty = ty.rename(columns={
    '#ty': 'Date', 'Unnamed: 1': 'Open', 'Unnamed: 2': 'High',
    'Unnamed: 3': 'Low', 'Unnamed: 4': 'Close', 'Unnamed: 5': 'NC','Unnamed: 6': 'PC%', 
    'Unnamed: 7': 'Roll', 'Unnamed: 8': 'SynTY', 'M  O   V   I   N   G   A   V   E   R   A   G   E  S': 'ma10'
})

In [8]:
ty

,Date,Open,High,Low,Close,NC,PC%,Unnamed: 7,SynTY,ma10,...,THESE ARE FOR BREAKOUT,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,CORRELATIONS,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,#Date,Open,High,Low,Close,NC,PC(%),Roll,100.000000,ma10,...,Hi30,Low30,action,position,BrkRet30,NaN,TenThirty,Thirty 100,Eigthy 160,Brkout30
1,19990308,114.46875,114.6875,114.375,114.4375,0.09375,0.08199,0,100.081990,NaN,...,NaN,NaN,NaN,NaN,NaN,TenThirty,1,NaN,NaN,NaN
2,19990309,114.25,115.125,114.125,115,0.5625,0.491535,0,100.573927,NaN,...,NaN,NaN,NaN,NaN,NaN,Thirty 100,NaN,1,NaN,NaN
3,19990310,115.03125,115.125,114.6875,114.875,-0.125,-0.108696,0,100.464608,NaN,...,NaN,NaN,NaN,NaN,NaN,Eigthy 160,NaN,NaN,1,NaN
4,19990311,114.78125,115.09375,114.625,114.875,0,0,0,100.464608,NaN,...,NaN,NaN,NaN,NaN,NaN,Brkout30,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2979,20101227,119.28125,119.953125,119.21875,119.9375,0.4062,0.3399,0,165.143867,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2980,20101228,120.03125,120.1875,118.953125,119.046875,-0.8906,-0.7426,0,163.917509,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2981,20101229,119.03125,120.265625,118.953125,120.25,1.2031,1.0106,0,165.574059,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2982,20101230,120,120.203125,119.578125,119.984375,-0.2656,-0.2209,0,165.208306,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2983,20101231,120.359375,120.484375,119.9375,120.34375,0.3594,0.2995,0,165.703105,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN